'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''


fib = [1,2]
fib_sum = 2
while fib[-1] < 4e6:
    
    fib.append(fib[0] + fib[1])
    del fib[0]
    if fib[-1]%2 == 0:
        fib_sum += fib[-1]

print fib_sum
    
    
